#' @title Stacked bar plot of enzyme HMM hits by phylum
#'
#' @description
#' Visualize the distribution of enzyme HMM hits across phyla using a stacked
#' bar chart. Each bar represents a phylum, and each segment corresponds to
#' a specific enzyme.
#'
#' @param df_phylum_enzyme
#' Tidy data.frame with columns: Phylum, enzyme_id, hit_count.
#'
#' @param cfg
#' Configuration list generated by default_plot_config().
#'
#' @return
#' A ggplot object.
#'
#' @export
plot_phylum_enzyme_bar <- function(df_phylum_enzyme, cfg) {
  
  # Validate input format early to fail fast and clearly
  if (!is.data.frame(df_phylum_enzyme)) {
    stop("df_phylum_enzyme must be a data.frame with columns Phylum, enzyme_id, hit_count")
  }
  
  # Ensure a valid configuration object is available
  if (missing(cfg) || !is.list(cfg)) {
    cfg <- default_plot_config()
  }
  
  ggplot2::ggplot(
    df_phylum_enzyme,
    ggplot2::aes(
      x = Phylum,               # x-axis represents phyla
      y = hit_count,            # y-axis shows number of HMM hits
      fill = enzyme_id          # fill color encodes enzyme identity
    )
  ) +
    ggplot2::geom_bar(
      stat = "identity",        # bar heights represent actual values
      color = "grey30"          # thin border for readability
    ) +
    ggplot2::scale_fill_viridis_d(
      option = cfg$palette_enzyme
    ) +
    ggplot2::theme_minimal(
      base_size = cfg$base_font_size
    ) +
    ggplot2::theme(
      plot.title = ggplot2::element_text(
        hjust = 0.5,             # center title
        face = "bold",
        size = cfg$title_size
      ),
      axis.text.x = ggplot2::element_text(
        angle = 90,              # rotate labels for dense categories
        vjust = 0.5,
        hjust = 1,
        size = cfg$axis_text_size
      ),
      axis.text.y = ggplot2::element_text(
        size = cfg$axis_text_size
      )
    ) +
    ggplot2::labs(
      title = "Distribution of enzyme HMM hits across Phyla",
      x = NULL,
      y = "HMM hits"
    )
}