#' @title Heatmap of enzyme abundance by taxon or phylum
#'
#' @description
#' Generate a heatmap of enzyme counts aggregated either at taxon or phylum level.
#' This function is intended for exploratory visualization, not for statistical
#' inference.
#'
#' @details
#' Log-transformation (log10(x + 1)) is applied only to improve visual contrast
#' when values span multiple orders of magnitude.
#'
#' @param taxon_enzyme_mat
#' Numeric matrix with rows = taxa and columns = enzymes.
#'
#' @param phylum_enzyme_mat
#' Numeric matrix with rows = phyla and columns = enzymes.
#'
#' @param meta_taxa
#' Data.frame mapping taxon_id to Phylum.
#'
#' @param cfg
#' Configuration list generated by default_plot_config().
#'
#' @param draw
#' Logical. If TRUE, the heatmap is drawn immediately.
#'
#' @return
#' A ComplexHeatmap::Heatmap object.
#'
#' @export
plot_enzyme_heatmap <- function(
    taxon_enzyme_mat,
    phylum_enzyme_mat,
    meta_taxa,
    cfg,
    draw = FALSE
) {
  
  # Check required packages locally to avoid global side effects
  if (!requireNamespace("ComplexHeatmap", quietly = TRUE)) {
    stop("Package 'ComplexHeatmap' is required.")
  }
  if (!requireNamespace("circlize", quietly = TRUE)) {
    stop("Package 'circlize' is required.")
  }
  if (!requireNamespace("grid", quietly = TRUE)) {
    stop("Package 'grid' is required.")
  }
  
  if (missing(cfg) || !is.list(cfg)) {
    cfg <- default_plot_config()
  }
  
  # ------------------------------------------------------------
  # SELECT DATA LEVEL (TAXON OR PHYLUM)
  # ------------------------------------------------------------
  
  if (identical(cfg$heatmap_row_level, "Phylum")) {
    
    # Use phylum-level matrix directly
    mat <- phylum_enzyme_mat
    row_title <- "Phylum"
    left_ann <- NULL
    
  } else {
    
    # Use taxon-level matrix and annotate rows by phylum
    mat <- taxon_enzyme_mat
    
    if (is.null(rownames(mat))) {
      stop("taxon_enzyme_mat must have rownames corresponding to taxon IDs.")
    }
    
    # Map taxa to phyla using metadata
    idx <- match(rownames(mat), meta_taxa$taxon_id)
    phylum_vec <- meta_taxa$Phylum[idx]
    
    left_ann <- ComplexHeatmap::rowAnnotation(
      Phylum = phylum_vec,
      show_annotation_name = TRUE
    )
    
    row_title <- "Taxon"
  }
  
  # ------------------------------------------------------------
  # OPTIONAL ROW FILTERING (TOP-N)
  # ------------------------------------------------------------
  
  if (!is.null(cfg$heatmap_top_n_taxa)) {
    totals <- rowSums(as.matrix(mat), na.rm = TRUE)
    keep <- names(sort(totals, decreasing = TRUE))[
      seq_len(min(cfg$heatmap_top_n_taxa, length(totals)))
    ]
    mat <- mat[keep, , drop = FALSE]
  }
  
  # ------------------------------------------------------------
  # DATA TRANSFORMATION (VISUAL ONLY)
  # ------------------------------------------------------------
  
  mat <- as.matrix(mat)
  storage.mode(mat) <- "numeric"
  
  if (isTRUE(cfg$heatmap_log)) {
    mat <- log10(mat + 1)
    legend_title <- "log10(hits + 1)"
  } else {
    legend_title <- "hits"
  }
  
  # ------------------------------------------------------------
  # COLOR SCALE
  # ------------------------------------------------------------
  
  rng <- range(mat, na.rm = TRUE)
  mid <- stats::median(mat, na.rm = TRUE)
  
  col_fun <- circlize::colorRamp2(
    c(rng[1], mid, rng[2]),
    c("#f7fbff", "#9ecae1", "#08306b")
  )
  
  # ------------------------------------------------------------
  # HEATMAP OBJECT
  # ------------------------------------------------------------
  
  hm <- ComplexHeatmap::Heatmap(
    mat,
    name = legend_title,
    col = col_fun,
    left_annotation = left_ann,
    cluster_rows = cfg$heatmap_cluster_rows,
    cluster_columns = cfg$heatmap_cluster_cols,
    show_row_names = TRUE,
    show_column_names = TRUE,
    row_title = row_title,
    column_title = "Enzymes",
    row_names_gp = grid::gpar(fontsize = cfg$heatmap_row_label_size),
    column_names_gp = grid::gpar(fontsize = cfg$heatmap_col_label_size)
  )
  
  if (isTRUE(draw)) {
    ComplexHeatmap::draw(hm, column_title = cfg$heatmap_title)
  }
  
  ## ----------------------------
  ## Save
  ## ----------------------------
  if (isTRUE(cfg$save)) {
    if (!dir.exists(cfg$output_dir)) {
      dir.create(cfg$output_dir, recursive = TRUE, showWarnings = FALSE)
    }
    
    png(
      filename = file.path(cfg$output_dir, "heatmap.png"),
      width = cfg$width,
      height = cfg$height,
      units = "in",
      res = cfg$dpi
    )
    ComplexHeatmap::draw(hm, column_title = cfg$heatmap_title)
    dev.off()
  }
  
  invisible(hm)
}
